import React from 'react';
const AppContent = React.createContext();           //  ../../assets/

export const AppProvider = ({children})=>{
    
    const states = [{name: "Andhra Pradesh", id:'1'}, 
                    {name: "Arunachal Pradesh", id:'2'},
                    {name: "Assam", id: '3'},
                    {name: "Bihar", crop:"", id: '4'},
                    {name: "Chhattisgarh", crop:"", id: '5'},
                    {name: "Goa", crop:"", season:"", id: '6'},
                    {name: "Gujarat", crop:"", id: '7'},
                    {name: "Haryana", crop:"", season:"", id: '8'},
                    {name: "Himachal Pradesh", id: '9'},                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                    {name: "Jammu And Kashmir", id: '10'},
                    {name: "Jharkhand", id: '11'},
                    {name: "Karnataka", crop:"", id: '12'},
                    {name: "Kerala", crop:"", id: '13'},
                    {name: "Madhya Pradesh", id: '14'},
                    {name: "Maharashtra", id: '15'},
                    {name: "Manipur", id: '16'},
                    {name: "Meghalaya", id: '17'},
                    {name: "Mizoram", id: '18'},
                    {name: "Nagaland", id: '19'},
                    {name: "New Delhi", id: '20'},
                    {name: "Odisha", id: '21'},
                    {name: "Punjab", id: '22'},
                    {name: "Rajasthan", id: '23'},
                    {name: "Sikkim", id: '24'},
                    {name: "Tamil Nadu", id: '25'},
                    {name: "Telangana", id: '26'},
                    {name: "Tripura", id: '27'},
                    {name: "Uttar Pradesh", id: '28'},
                    {name: "Uttarakhand", id: '29'},
                    {name: "West Bengal", id: '30'}               

    ]
    
    const flowers = [ {id: 1, common : "Cut rose", image : require("../../assets/cut_rose.jpg"), url: 'https://www.youtube.com/watch?v=phsMXM4vtz8', text: "Cut flowers are flowers or flower buds (often with some stem and leaf) that have been cut from the plant bearing it. It is usually removed from the plant for decorative use. Typical uses are in vase displays, wreaths and garlands. Many gardeners harvest their own cut flowers from domestic gardens, but there is a significant floral industry for cut flowers in most countries. The plants cropped vary by climate, culture and the level of wealth locally. Often the plants are raised specifically for the purpose, in field or glasshouse growing conditions. Cut flowers can also be harvested from the wild." },
                      {id: 2,common : "Cut Chrysanthemum", image : require("../../assets/cut_chrysanthemum.jpg"), url: 'https://www.youtube.com/watch?v=jwtmeilzA80', text: "It is native to the northern hemisphere chiefly Europe and Asia. Historically, Confucius the great Chinese philosopher has, in his writing, mentioned chrysanthemum as early as in 500 BC making it one of the most ancient cultivated flower of the world. In England, the popularity of chrysanthemum as exhibition flower is at its peak. It has second ranks as commercial crop. In the United States, it is the number one dollar earner flower and the most reliable. It is difficult to say with certainty when its culture began in India. Shant Gyanehswar has mentioned it in his famous Marathi exposition of Gita “Gyaneshwari” written in AD 1290. The Hindi name guldaudi (meaning flower of Daud) suggests that it must have been grown during the Moghul period in this country."},
                      {id: 3,common : "Carnation", image : require("../../assets/carnation.jpg"), url: 'https://www.youtube.com/watch?v=f3cDPiFr5Qo', text: "Carnation, (Dianthus caryophyllus), also called grenadine or clove pink, herbaceous plant of the pink, or carnation, family (Caryophyllaceae), native to the Mediterranean area. It is widely cultivated for its fringe-petaled flowers, which often have a spicy fragrance, and is used extensively in the floral industry. Carnations are among the most popular commercial cut flowers, being used in floral arrangements, corsages, and boutonnieres. In 1907 Anna Jarvis of Philadelphia selected the pink carnation as the symbol for Mother’s Day. In Europe the carnation was formerly used as a treatment for fevers. It was also used to spice wine and ale during Elizabethan times, as a substitute for the more expensive clove (Syzygium aromaticum)."},
                      {id: 4,common : "Anthurium", image : require("../../assets/anthurium.jpg"), url: 'https://www.youtube.com/watch?v=VS4tEf1KVI8', text: "Anthuriums are herbaceous epiphytes native to tropical America. Anthurium is a genus of more than 800 species found in the New World tropics from Mexico to northern Argentina and Uruguay. The Anthurium is also known as Painted Tongue, Flamingo Flower (Flamingo Lily) or Tail Flower. Anthuriums are grown for their brightly colored flower spathes and their ornamental leaves."},
                      {id: 5,common : "Dendrobium Orchid", image : require("../../assets/orchid.jpg"), url: 'https://www.youtube.com/watch?v=8Lc4Htux1uM', text: "Dendrobium is a genus of mostly epiphytic and lithophytic orchids in the family Orchidaceae. It is a very large genus, containing more than 1,800 species that are found in diverse habitats throughout much of south, east and southeast Asia, including China, Japan, India, the Philippines, Indonesia, Australia, New Guinea, Vietnam and many of the islands of the Pacific. Orchids in this genus have roots that creep over the surface of trees or rocks, rarely having their roots in soil. Up to six leaves develop in a tuft at the tip of a shoot and from one to a large number of flowers are arranged along an unbranched flowering stem. Several attempts have been made to separate Dendrobium into smaller genera, but most have not been accepted by the World Checklist of Selected Plant Families."},
                      {id: 6,common : "Lilium", image : require("../../assets/lilium.jpg"), url: 'https://www.youtube.com/watch?v=o3E_AKwgCYM', text: "Lilium (members of which are true lilies) is a genus of herbaceous flowering plants growing from bulbs, all with large prominent flowers. Lilies are a group of flowering plants which are important in culture and literature in much of the world. Most species are native to the temperate northern hemisphere, though their range extends into the northern subtropics. Many other plants have 'lily' in their common name but are not related to true lilies."},
                      {id: 7,common : "Gladious", image : require("../../assets/gladiolus.jpg"), url: 'https://www.youtube.com/watch?v=ZXtTI7mv23g', text: "Gladiolus, (genus Gladiolus), also called gladiola, plural gladioli, gladiolus, orgladioluses, genus of about 300 species of flowering plants of the iris family (Iridaceae), native to Europe, Africa, and the Mediterranean area. Several species are widely cultivated for cut flowers and as garden ornamentals. Gladiolus have been grown and loved by generations of gardeners. These summer-blooming bulbs produce elegant, 3-foot flower spikes with orchid-like blooms. They look spectacular in a vase and are suitable for growing in flower gardens, container gardens and even vegetable gardens. Gladiolas are available in a rainbow of gorgeous colors, ranging from white, yellow, pink and lavender, to rose, burgundy, purple and even green. The bulbs are incredibly easy to grow. Just plant them in spring for flowers in late summer." },
                      {id: 8,common : "Gerbera", image : require("../../assets/gerbera.jpg"), url: 'https://www.youtube.com/watch?v=syycvCRinjU', text: "Gerbera is commonly known as Transvaal daisy or Bar berton daisy or African daisy. It is an important commercial cut flower crop. Gerbera flowers have a wide range of colours including yellow, orange, cream-white, pink, brick red, red, terracotta and various other intermediate colors. In double varieties, bicolor flowers are also available. Gerbera flower stalks are long, thin and leafy and have a long vase life. Gerbera is commonly known as Transvaal daisy or Bar berton daisy or African daisy. It is an important commercial cut flower crop. Gerbera flowers have a wide range of colours including yellow, orange, cream-white, pink, brick red, red, terracotta and various other intermediate colors. In double varieties, bicolor flowers are also available. Gerbera flower stalks are long, thin and leafy and have a long vase life. The major producing states in India are Karnataka, Maharashtra, Tamilnadu, West Bengal, Himachal Pradesh, Jammu & Kashmir and Gujarat."},
                      {id: 9,common : "China Aster", image : require("../../assets/china aster.jpg"), url: 'https://www.youtube.com/watch?v=XtFX8yIZy3w', text:"China aster, also called Annual Aster, (Callistephus chinensis), herbaceous plant of the aster family (Asteraceae, also called Compositae), many cultivated varieties of which are longtime garden favourites. The native species from China is 75 cm (2.5 feet) tall, with white to violet flowers having yellow centres. The cultivated varieties vary in height from 20 cm to 1 m (8 inches to 3 feet) tall. The flower heads, up to 12 cm (about 5 inches) across, are often totally composed of petallike ray flowers; they range in colour from white and pale yellow to pink, rose, red, blue, purple, and violet."},
                      {id: 10,common : "Golden Rod", image : require("../../assets/goldenrod.jpg"), url: 'https://www.youtube.com/watch?v=Y3sYFKh3jHU', text: "Goldenrod grows in Europe, Asia, and North and South America. It flourishes in roadside ditches and fields and is often considered a weed. The plant's yellow flowers bloom in late summer and early fall. It cross-pollinates easily with other plants, so there are more than 100 different species of goldenrod. Goldenrod is a common name for many species of flowering plants in the sunflower family, Asteraceae, commonly in reference to the genus Solidago. Several genera, such as Euthamia, were formerly included in a broader concept of the genus Solidago. Some authors treat Oligoneuron, the flat-topped goldenrods, as a separate genus than Solidago, while others consider it a section: Solidago sect."},
                      {id: 11,common : "Rose", image : require("../../assets/rose.jpg"), url: 'https://www.youtube.com/watch?v=9xAGMGHzSw0', text: "Rose, (genus Rosa), genus of some 100 species of perennial shrubs in the rose family (Rosaceae). Roses are native primarily to the temperate regions of the Northern Hemisphere. Many roses are cultivated for their beautiful flowers, which range in colour from white through various tones of yellow and pink to dark crimson and maroon, and most have a delightful fragrance, which varies according to the variety and to climatic conditions. Most rose species are native to Asia, with smaller numbers being native to North America and a few to Europe and northwest Africa. Roses from different regions of the world hybridize readily, giving rise to types that overlap the parental forms, and making it difficult to determine basic species. Fewer than 10 species, mostly native to Asia, were involved in the crossbreeding that ultimately produced today’s many types of garden roses."},
                      {id: 12,common : "Malligai", image : require("../../assets/malligai.jpg"), url: 'https://www.youtube.com/watch?v=dcHmW_f4j_U', text: "Malligai Poo means Jasmine Flower in English. The first and popular characteristic of jasmine is the fragrance of the flower which is increasingly at night. The aroma of jasmine is very often used as a perfume and cosmetic ingredients. Jasmine thrives in warm climates. This flower has green leaves and delicate flowers. Jasminum sambac is a small shrub or vine growing up to 0.5 to 3 m (1.6 to 9.8 ft) in height. It is widely cultivated for its attractive and sweetly fragrant flowers. The flowers may be used as a fragrant ingredient in perfumes and jasmine tea. In India it is very popular and is known as Mogra. It is the national flower of the Philippines, where it is known as sampaguita, as well as being one of the three national flowers of Indonesia, where it is known as melati putih."},
                      {id: 13,common : "Mullai" , image : require("../../assets/mullai.jpg"), url: 'https://www.youtube.com/watch?v=OXhwP13XClw', text: "Mullai is a sweet smelling plant that is renowned for its ornamental beauty and distinctive fragrance. Jasmine is also used frequently in making tea, syrup and essential oils. Mullai has small white flowers, although some species have bright yellow, with long shoots that climb. Typically, each flower will have about four to nine petals, two locules, and one to four ovules, with two stamens and very short filaments. Mullai plants are native to the Himalayas in China and like warm tropical climates. It can also be found growing in the wild in Sri Lanka, Iran and Kashmir. Mullai should be planted in your garden between June and November and it can be grown from taking a cutting from an old plant. This cutting can then be potted on until a new Mullai bush, or shrub, is ready to be planted into your garden. When planting more than one Jasmine plant, at least eight feet should be left between plants to allow for growth. Mullai plants come from the family of the Oleaceae and the genus of Mullai. There are several different varieties of Mullai including the Primrose Mullai, Italian Mullai and Winter Mullai."},
                      {id: 14,common : "Jathi Malli", image : require("../../assets/jathimalli.jpg"), url: 'https://www.youtube.com/watch?v=hJh6obXy8-I', text: "Jasmine is a very beautiful and fragrant flower. But,  Everyone will have the desire to grow this at home. Those who do not have space at home will have to grow in pots. So, we can also easily grow jasmine in the pot. The jasmine plant blooms, it dries and blooms. Only those branches should be cut off. Once you pluck the buds from a branch that branch will start to dry out. Although, Only then will the new branch sprout and give you plenty of flowers. If left uncut it will grow wild and wither. Jasminum Grandiflorum is a deciduous shrub, best suited for outdoor use. Jasminum is found throughout Asia, Africa, and the Middle East. But, Many assume Jasminum Grandiflorum with the common name ‘Spanish Jasmine’ and Jasminum officinale “Poet’ s Jasmine” are the same jasmine plants but they are different species. The Spanish Jasminum features white flowers with thin petals. Some cultures, use the leaves for herbal medicine and the flowers for the scent of Jasmine in perfumes. Jasmines are native to tropical and subtropical regions and introduced in the mid-sixteenth century. Among the large number of species existing, only three species have attained importance in commercial cultivation."},
                      {id: 15,common : "Crossandra", image : require("../../assets/crossandra.jpg"), url: 'https://www.youtube.com/watch?v=RpjFOiPm-PM', text: "Crossandra infundibuliformis, the firecracker flower, is a species of flowering plant in the family Acanthaceae, native to southern India and Sri Lanka. It is most often found in south Indian region Malenadu and Kerala. Indoors, crossandra is a lovely flowering houseplant for bright spots. Accent it with a contrasting container (we think purple or white pots are stunning against the flowers) or complement its beautiful blooms with a terra-cotta container. "},
                      {id: 16,common : "Chrysanthemum" , image : require("../../assets/chrysanthemum.jpg"), url: 'https://www.youtube.com/watch?v=fnyEPVrivYs' , text: "The Chrysanthemum is the flower of the month for November, and this beautiful flower comes with a wide variety of meanings all across the globe. In Asia the chrysanthemum signifies life and rebirth, making them great gifts for birthdays and baby showers. In Europe the chrysanthemum signifies an expression of sympathy. Chrysanthemum’s are typically looked at as a flower that signifies respect and honor in America. The color of the flower can also affect the meaning behind the chrysanthemum. For example, if you receive a red chrysanthemum from someone, it is a symbol of love. A yellow chrysanthemum blossom on the other hand signifies neglected love or sorrow. A white chrysanthemum is a symbol of loyalty and devoted love. In general, chrysanthemums are believed to represent happiness, love, longevity and joy."},
                      {id: 17,common : "Marigold", image : require("../../assets/Marigold.jpg"), url: 'https://www.youtube.com/watch?v=G8EjPPHt8xI', text: "The common English name is derived from “Mary’s Gold”, yet the Latin name Tagetes is from the Roman mythology, named after Tages who was the founding prophet of the Etruscan religion, who according to legend, appeared at plow-time and taught the Etruscans divination. Perhaps for this reason, Tagetes took its namesake because it grows well in almost any sort of soil, with unusual tolerance to drought. Marigolds are one of the most popular annual flowers, easily grown from seed or transplant, and when given the right conditions will overflow with bright blossoms that fill the garden with cheerful color. Marigolds are equally suitable for containers, as they are in the garden, and are even grown as a long-lasting cut flower, with a clean, crisp scent."},
                      {id: 18,common : "Tuberrose" , image : require("../../assets/tuberose.jpg"), url: 'https://www.youtube.com/watch?v=beMypW26V98' , text: "Tuberose (Polianthes tuberosa L.)is one of the most important tropical ornamental bulbous flowering plants cultivated for production of long lasting flower spikes. It is popularly known as Rajanigandha or Nishigandha. It belongs to the family Amaryllidaceae and is native of Mexico. Tuberose is an important commercial cut as well as loose flower crop due to pleasant fragrance, longer vase-life of spikes, higher returns and wide adaptability to varied climate and soil. They are valued much by the aesthetic world for their beauty and fragrance. The flowers are attractive and elegant in appearance with sweet fragrance. It has long been cherished for the aromatic oils extracted from its fragrant white flowers. Tuberose blooms throughout the year and its clustered spikes are rich in fragrance; florets are star shaped, waxy and loosely arranged on spike that can reach up to 30 to 45 cm in length.The flower is very popular for its strong fragrance and its essential oil is important component of high- grade perfumes. ‘Single’ varieties are more fragrant than ‘Double’ type and contain 0.08 to 0.14 percent concrete which is used in high grade perfumes."},
                      {id: 19,common : "Nerium" , image : require("../../assets/nerium.jpg"), url: 'https://www.youtube.com/watch?v=YFVCLRkcQYs', text: "Nerium oleander /ˈnɪəriəm ˈoʊliːændər/, most commonly known as oleander or nerium, is a shrub or small tree cultivated worldwide in temperate and subtropical areas as an ornamental and landscaping plant. It is the only species currently classified in the genus Nerium, belonging to subfamily Apocynoideae of the dogbane family Apocynaceae. It is so widely cultivated that no precise region of origin has been identified, though it is usually associated with the Mediterranean Basin." },              
    ]

    const one = {
        Varieties : "Gladiator, Baby Pink, Sofia Lawrence, YCD 1, YCD 2, YCD 3 are commonly cultivated.",
        Soil_and_climate : "It is generally suitable for higher elevation (1500 m and above). It can also be grown in the plains under ideal condition of fertile loamy soils with salt-free irrigation water. The ideal climate for rose growing should have temperature with a minimum of 15°C and maximum of 28°C. Light is important factor which decides the growth. The growth is slowed by day length, i.e. > 12 hours and heavy overcast, cloudy/mist conditions. High relative humidity exposes the plant to serious fungal diseases. In tropics the ideal temperature is 25°C – 30°C on sunny day and on cloudy day 18°C – 20°C. The optimum temperature should be 15°C – 18°C. These temperatures are extremely difficult to find and it’s therefore to compromise.",
        Propagation_and_planting : "The crop can be propagated by rooted cuttings or by budding on Briar root stocks in hills and on Edward Rose and Rosa indica in plains. One year old budded plants are planted in July - August at 75 cm x 75 cm spacing.",
        Planting_of_Rose : { After_cultivation : "The plants should be watered daily until they establish and thereafter once in a week. Pruning is done during March and October. Spray Diuran 2.5 kg a.i/ha to control weeds.  Avoid spray fluid coming in contact with Rose plants.", 
                             Support_of_the_plants : "Post is placed at internals of 3m on both sides of the bed. Along the sides of the bed, galvanized wires or plastic string are fastened at the posts at 30cm – 40cm intervals to support the plant. Between the wires across the bed, thin strings can be tied to keep the width of the beds constant.",
                             Disbudding : "Varieties produce some side buds below the center bud. These side buds have to be removed or disbudded. The disbudding must be done regularly and also as soon as possible in order to avoid large wounds in the upper leaf axil.",
                             Dead_shoot_removal : "In the old plants the dead shoot or dried shoots on plants will serve as the host for fungi. So regularly these have to be removed.",
                             Soil_loosening_on_beds : "After 6 months or so, there is every chance that the soil become stony and it has to be loosened for efficient irrigation.",
                            },
    }

    return <AppContent.Provider value={{ data : states, dataa : flowers}}>
        {children}
    </AppContent.Provider>
};

export default AppContent;
